FROM registry-nginxinc.rhcloud.com/nginx/rhel7-nginx:1.9.2

#COPY cert.crt /etc/nginx/
#COPY cert.key /etc/nginx/
COPY default.conf /etc/nginx/conf.d/
#
#RUN chmod -R 777 /var/log/nginx /var/cache/nginx/ \
#	&& chmod -R 777 /var/run \
#	&& chmod 644 /etc/nginx/*
